name: Pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # packages from requirements.txt are needed to eliminate errors when importing functions to be tested
          pip install -r requirements.txt
      - name: Run tests
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          python -m pytest
